pub(crate) mod bbox_manager;
pub(crate) mod gpu_manager;
pub(crate) mod renderer;
pub(crate) mod hdr_frame;
pub(crate) mod light_manager;
pub(crate) mod mesh_manager;
pub(crate) mod pipeline_manager;
pub(crate) mod renderpass;
pub(crate) mod skybox_manager;
pub(crate) mod texture;
pub(crate) mod uniform;
pub(crate) use renderer::Renderer;
pub(crate) mod gpu_material_cache;
pub(crate) mod gpu_mesh_cache;
pub(crate) mod gpu_texture_cache;
pub(crate) mod imgui_renderer;

pub(crate) use bbox_manager::BBoxManager;
pub(crate) use gpu_manager::{GpuManager, LayoutKind};
pub(crate) use renderer::GpuDevice;
pub(crate) use hdr_frame::{HdrFrame, IDTexture};
pub(crate) use light_manager::LightManager;
pub(crate) use pipeline_manager::PipelineManager;
pub(crate) use skybox_manager::SkyboxManager;
pub(crate) use uniform::{CameraUniform, GlobalUniform, LightUniform, MaterialUniform, ModelUniform};

pub(crate) use crate::assets::*;
pub(crate) use gpu_material_cache::*;
pub(crate) use gpu_mesh_cache::*;
pub(crate) use gpu_texture_cache::*;
pub(crate) use imgui_renderer::{ImGuiTextureRegistry, ImguiRender, UiTextureResolver, UiTexture};
pub(crate) use texture::GpuTexture;