name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wgpu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan1 mesa-vulkan-drivers

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
      - name: Cargo Build
        run: cargo test --no-run --release

      - name: Upload test binaries
        uses: actions/upload-artifact@v4
        with:
          name: test-binaries
          path: target/release/deps
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Install wgpu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan1 mesa-vulkan-drivers 

      - name: Download test binaries
        uses: actions/download-artifact@v4
        with:
          name: test-binaries
          path: target/release/deps

      - name: Run tests (force software backend)
        run: |
          export WGPU_BACKEND=gl
          esport WGPU_POWER_PREF=low
          cargo test --release -- no-fail-test

  run:
    name: Run Application (short)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
         toolchain: stable
         
      - name: Install wgpu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan1 mesa-vulkan-drivers

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-binaries
          path: target/release/deps

      - name: Run App (30s)
        run: |
          export WGPU_BACKEND=gl
          esport WGPU_POWER_PREF=low
          cargo run --release
        timeout-minutes: 1
        continue-on-error: true
