name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # -----------------------------
  # Job: Build
  # -----------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install wgpu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan1 mesa-vulkan-drivers

      - name: Build App
        run: cargo build

  # -----------------------------
  # Job: Test
  # -----------------------------
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install wgpu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan1 mesa-vulkan-drivers

      - name: Run tests 
        run: cargo test

  # -----------------------------
  # Job: Run application
  # -----------------------------
  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install wgpu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan1 mesa-vulkan-drivers  xvfb
          
      - name: Install Linux dependencies
        run: |
          sudo apt-get install -y \
            libxkbcommon-x11-0 \
            libxkbcommon-dev \
            libxi6 \
            libxcursor1 \
            libxrandr2 \
            libx11-xcb1 \
            libgl1 \
            mesa-utils
            
      - name: Copy assets to target/release
        run: cp -r assets target/debug/

      - name: Run App (30s max)
        run: |
          export WGPU_BACKEND=gl
          export WGPU_POWER_PREF=low
          xvfb-run -s "-screen 0 1024x768x24" cargo run --bin ci_runner
