name: Rust Windows

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - uses: dtolnay/rust-toolchain@stable
    - name: Build (Debug)
      run: cargo build --verbose
    - name: Run tests
      env:
        WGPU_BACKEND: noop
      run: cargo test --verbose
