name: Rust macOS

on:
  push:
    branches: 
      - master
      - "**"   # qualunque branch
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - uses: dtolnay/rust-toolchain@stable
    - name: Build (Debug)
      run: cargo build --verbose

    # 👇 se i test falliscono perché non trova l'adapter WGPU,
    # puoi abilitarli solo con backend NOOP
    # - name: Run tests (headless)
    #   env:
    #     WGPU_BACKEND: noop
    #   run: cargo test --verbose
