name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxcursor-dev libxrandr-dev \
              libxi-dev libgl1-mesa-dev libudev-dev pkg-config

      - uses: dtolnay/rust-toolchain@stable

      - name: Build (Debug)
        run: cargo build

      - name: Test (headless)
        run: cargo test
        env:
          WGPU_BACKEND: noop

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build (Debug)
        run: cargo build

      - name: Test (headless)
        run: cargo test
        env:
          WGPU_BACKEND: noop

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build (Debug)
        run: cargo build

      - name: Test (real DX12)
        run: cargo test
