name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Step per installare dipendenze Vulkan/mesa per wgpu headless
    - name: Install wgpu dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y \
       libvulkan1 \
       mesa-utils \
       mesa-vulkan-drivers \
       vulkan-tools
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
